<?php

use Illuminate\Database\Seeder;

class PermissionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [

            ['id' => 1, 'title' => 'user_management_access',],
            ['id' => 2, 'title' => 'permission_access',],
            ['id' => 3, 'title' => 'permission_create',],
            ['id' => 4, 'title' => 'permission_edit',],
            ['id' => 5, 'title' => 'permission_view',],
            ['id' => 6, 'title' => 'permission_delete',],
            ['id' => 7, 'title' => 'role_access',],
            ['id' => 8, 'title' => 'role_create',],
            ['id' => 9, 'title' => 'role_edit',],
            ['id' => 10, 'title' => 'role_view',],
            ['id' => 11, 'title' => 'role_delete',],
            ['id' => 12, 'title' => 'user_access',],
            ['id' => 13, 'title' => 'user_create',],
            ['id' => 14, 'title' => 'user_edit',],
            ['id' => 15, 'title' => 'user_view',],
            ['id' => 16, 'title' => 'user_delete',],
            ['id' => 17, 'title' => 'user_action_access',],
            ['id' => 18, 'title' => 'user_action_create',],
            ['id' => 19, 'title' => 'user_action_edit',],
            ['id' => 20, 'title' => 'user_action_view',],
            ['id' => 21, 'title' => 'user_action_delete',],
            ['id' => 22, 'title' => 'internal_notification_access',],
            ['id' => 23, 'title' => 'internal_notification_create',],
            ['id' => 24, 'title' => 'internal_notification_edit',],
            ['id' => 25, 'title' => 'internal_notification_view',],
            ['id' => 26, 'title' => 'internal_notification_delete',],
            ['id' => 27, 'title' => 'channel_server_access',],
            ['id' => 28, 'title' => 'sync_server_access',],
            ['id' => 29, 'title' => 'system_default_access',],
            ['id' => 30, 'title' => 'channel_server_create',],
            ['id' => 31, 'title' => 'channel_server_edit',],
            ['id' => 32, 'title' => 'channel_server_view',],
            ['id' => 33, 'title' => 'channel_server_delete',],
            ['id' => 34, 'title' => 'channel_access',],
            ['id' => 35, 'title' => 'channel_create',],
            ['id' => 36, 'title' => 'channel_edit',],
            ['id' => 37, 'title' => 'channel_view',],
            ['id' => 38, 'title' => 'channel_delete',],
            ['id' => 39, 'title' => 'country_access',],
            ['id' => 40, 'title' => 'country_create',],
            ['id' => 41, 'title' => 'country_edit',],
            ['id' => 42, 'title' => 'country_view',],
            ['id' => 43, 'title' => 'country_delete',],
            ['id' => 44, 'title' => 'timezone_access',],
            ['id' => 45, 'title' => 'timezone_create',],
            ['id' => 46, 'title' => 'timezone_edit',],
            ['id' => 47, 'title' => 'timezone_view',],
            ['id' => 48, 'title' => 'filter_access',],
            ['id' => 49, 'title' => 'filter_create',],
            ['id' => 50, 'title' => 'filter_edit',],
            ['id' => 51, 'title' => 'filter_view',],
            ['id' => 52, 'title' => 'filter_delete',],
            ['id' => 53, 'title' => 'video_server_type_access',],
            ['id' => 54, 'title' => 'video_server_type_create',],
            ['id' => 55, 'title' => 'video_server_type_edit',],
            ['id' => 56, 'title' => 'video_server_type_view',],
            ['id' => 57, 'title' => 'video_server_type_delete',],
            ['id' => 58, 'title' => 'notification_server_type_access',],
            ['id' => 59, 'title' => 'notification_server_type_create',],
            ['id' => 60, 'title' => 'notification_server_type_edit',],
            ['id' => 61, 'title' => 'notification_server_type_view',],
            ['id' => 62, 'title' => 'notification_server_type_delete',],
            ['id' => 63, 'title' => 'protocol_access',],
            ['id' => 64, 'title' => 'protocol_create',],
            ['id' => 65, 'title' => 'protocol_edit',],
            ['id' => 66, 'title' => 'protocol_view',],
            ['id' => 67, 'title' => 'protocol_delete',],
            ['id' => 68, 'title' => 'csi_access',],
            ['id' => 69, 'title' => 'csi_create',],
            ['id' => 70, 'title' => 'csi_edit',],
            ['id' => 71, 'title' => 'csi_view',],
            ['id' => 72, 'title' => 'csi_delete',],
            ['id' => 73, 'title' => 'cso_access',],
            ['id' => 74, 'title' => 'cso_create',],
            ['id' => 75, 'title' => 'cso_edit',],
            ['id' => 76, 'title' => 'cso_view',],
            ['id' => 77, 'title' => 'cso_delete',],
            ['id' => 78, 'title' => 'syncserver_access',],
            ['id' => 79, 'title' => 'syncserver_create',],
            ['id' => 80, 'title' => 'syncserver_edit',],
            ['id' => 81, 'title' => 'syncserver_view',],
            ['id' => 82, 'title' => 'syncserver_delete',],
            ['id' => 93, 'title' => 'role_convention_access',],
            ['id' => 94, 'title' => 'role_convention_create',],
            ['id' => 95, 'title' => 'role_convention_edit',],
            ['id' => 96, 'title' => 'role_convention_view',],
            ['id' => 97, 'title' => 'role_convention_delete',],
            ['id' => 98, 'title' => 'environment_access',],
            ['id' => 99, 'title' => 'environment_create',],
            ['id' => 100, 'title' => 'environment_edit',],
            ['id' => 101, 'title' => 'environment_view',],
            ['id' => 102, 'title' => 'environment_delete',],
            ['id' => 108, 'title' => 'group_builder_access',],
            ['id' => 109, 'title' => 'group_access',],
            ['id' => 110, 'title' => 'group_create',],
            ['id' => 111, 'title' => 'group_edit',],
            ['id' => 112, 'title' => 'group_view',],
            ['id' => 113, 'title' => 'group_delete',],
            ['id' => 114, 'title' => 'instance_access',],
            ['id' => 115, 'title' => 'instance_create',],
            ['id' => 116, 'title' => 'instance_edit',],
            ['id' => 117, 'title' => 'instance_view',],
            ['id' => 118, 'title' => 'instance_delete',],
            ['id' => 119, 'title' => 'aggregation_server_access',],
            ['id' => 120, 'title' => 'aggregation_server_create',],
            ['id' => 121, 'title' => 'aggregation_server_edit',],
            ['id' => 122, 'title' => 'aggregation_server_view',],
            ['id' => 123, 'title' => 'aggregation_server_delete',],
            ['id' => 124, 'title' => 'host_access',],
            ['id' => 125, 'title' => 'host_create',],
            ['id' => 126, 'title' => 'host_edit',],
            ['id' => 127, 'title' => 'host_view',],
            ['id' => 128, 'title' => 'host_delete',],
            ['id' => 129, 'title' => 'status_access',],
            ['id' => 130, 'title' => 'status_create',],
            ['id' => 131, 'title' => 'status_edit',],
            ['id' => 132, 'title' => 'status_view',],
            ['id' => 133, 'title' => 'status_delete',],
            ['id' => 134, 'title' => 'sync_server_function_access',],
            ['id' => 135, 'title' => 'sync_server_function_create',],
            ['id' => 136, 'title' => 'sync_server_function_edit',],
            ['id' => 137, 'title' => 'sync_server_function_view',],
            ['id' => 138, 'title' => 'sync_server_function_delete',],

        ];

        foreach ($items as $item) {
            \App\Permission::create($item);
        }
    }
}
